config/routes.rb
AuthDemo::Application.routes.draw do
  resource :session, only: [:create, :destroy, :new]
  resource :user, only: [:create, :new, :show] do
    resource :counter, only: [:update]
  end
  get '/home' => 'static_pages#home'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    # no user with given username
    return nil if user.nil?

    # check user's password
    user.password_digest.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    # fetches the user we've logged in as
    return nil if self.session[:session_token].nil?
    @user ||= User.find_by(session_token: self.session[:session_token])
  end

  def log_in!(user)
    # force other clients to log out by regenerating token
    user.reset_session_token!
    # log this client in
    self.session[:session_token] = user.session_token
  end

  def log_out!
    self.session[:session_token] = nil
  end
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  def update
    current_user.counter = params[:user][:counter]
    current_user.save!
    redirect_to user_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # signs a user in
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      # no user with the given name!
      render :new
    else
      # sign the user in
      log_in!(@user)
      redirect_to user_url
    end
  end

  def destroy
    # sign a user out
    log_out!
    redirect_to new_session_url
  end

  def new
    # presents a login form
    render :new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    
  end

  def contact

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    # sign up the user
    @user = User.new(user_params)
    if @user.save
      # redirect them to the new user's show page
      log_in!(@user)
      redirect_to user_url
    else
      # input didn't pass validation; re-render sign up form.
      render :new
    end
  end

  def new
    # present form for signup
    @user = User.new # dummy user object
    render :new
  end

  def show
    # show the user's details (just their username)
    if current_user.nil?
      # let them log in
      redirect_to new_session_url
      return
    end

    @user = current_user
    render :show
  end

  protected
  def user_params
    self.params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BootstrapDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="nav navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse"
              data-target="#collapse-menu"
              aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="collapse-menu">
      <ul class="nav navbar-nav">
        <li><%= link_to("Home", home_url) %></li>
        <li><%= link_to("Contact", contact_url) %></li>
        <li><%= link_to("About", about_url) %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to("Sign In", new_session_url) unless current_user %></li>
        <% if current_user %>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <%= current_user.username %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to("Profile", user_url) if current_user %></li>
            <li><%= link_to("Sign Out", session_url, method: :delete) if current_user %></li>
          </ul>
        </div>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<div class="jumbotron">
  <h1>Give us a try!</h1>
  <div class="row">
    <div class="col-xs-5">
      <p>
        Our product will change your life! Just follow these four easy steps.
      </p>
    </div>
    <div class="col-xs-5 col-xs-offset-1">
      <p>Step 1: Buy our product</p>
      <p>Step 2: Use our product</p>
      <p>Step 3: See the results</p>
    </div>
  </div>
</div>
<div class="row">
  <h1>Meet the team:</h1>
</div>
<div class="row text-center">
  <div class="col-xs-3">
    <img src="http://longhollowwomen.com/wp-content/uploads/2013/02/99233806-bringing-home-new-cat-632x475.jpg" width="140" height="100" class="img-circle" />
    <h2>President</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec congue, augue vitae euismod sagittis, sem ex ultricies tellus, non fringilla tellus augue at odio. Quisque nec eleifend mi. Praesent vel magna sed arcu efficitur gravida.
    </p>
  </div>
  <div class="col-xs-3">
    <img src="http://i.ytimg.com/vi/8p4ZjrDkX6g/maxresdefault.jpg" width="140" height="100" class="img-circle" />
    <h2>Lead Engineer</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec congue, augue vitae euismod sagittis, sem ex ultricies tellus, non fringilla tellus augue at odio. Quisque nec eleifend mi. Praesent vel magna sed arcu efficitur gravida.
    </p>
  </div>
  <div class="col-xs-3">
    <img src="http://www.theprocrastiwriter.com/wp-content/uploads/2013/07/cat-dog-and-star-wars-funny.jpg" width="140" height="100" class="img-circle" />
    <h2>Office Goofball</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec congue, augue vitae euismod sagittis, sem ex ultricies tellus, non fringilla tellus augue at odio. Quisque nec eleifend mi. Praesent vel magna sed arcu efficitur gravida.
    </p>
  </div>
  <div class="col-xs-3">
    <img src="http://stuffpoint.com/cats/image/190797-cats-cute-kitty.jpg" width="140" height="100" class="img-circle" />
    <h2>Intern</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec congue, augue vitae euismod sagittis, sem ex ultricies tellus, non fringilla tellus augue at odio. Quisque nec eleifend mi. Praesent vel magna sed arcu efficitur gravida.
    </p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<div class="row">
  <div class="form-group col-xs-5 col-xs-offset-1">
    <div class="form-group">
      <label for="name_field">Your Name: </label>
      <input class="form-control" type="text" name="name" id="name_field">
    </div>
    <div class="form-group">
      <label for="email_field">Your Email: </label>
      <input class="form-control" type="text" name="email" id="email_field">
    </div>
    <div class="form-group">
      <label for="question_field">Question: </label>
      <textarea class="form-control" name="question" rows="8" cols="40" id="question_field"></textarea>
    </div>
    <div class="form-group">
      <input type="button" class="btn btn-primary" value="Submit">
    </div>
  </div>

  <div class="form-group col-xs-5 col-xs-offset-1">
    <table class="table table-striped">
      <tr>
        <th>
          Staff Member
        </th>
        <th>
          Title
        </th>
        <th>
          Phone Number
        </th>
      </tr>
      <tr>
        <td>
          Person 1
        </td>
        <td>
          Office of the CEO
        </td>
        <td>
          555-555-5555
        </td>
      </tr>
      <tr>
        <td>
          Person 2
        </td>
        <td>
          Recruiter
        </td>
        <td>
          555-555-5555
        </td>
      </tr>
      <tr>
        <td>
          Person 3
        </td>
        <td>
          IT
        </td>
        <td>
          555-555-5555
        </td>
      </tr>
    </table>

  </div>

</div>

app/views/static_pages/home.html.erb
<h1>Home</h1>

<div class="row">
  <div class="col-xs-12">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="http://i.istockimg.com/image-zoom/45488460/3/380/286/stock-photo-45488460-sunrise.jpg" >
          <div class="carousel-caption">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin blandit mauris vel pellentesque. Praesent congue eros quis metus efficitur accumsan. Sed vel tempus nibh. Donec suscipit quam fringilla ipsum rhoncus tincidunt. Aenean nunc tellus, vulputate vulputate tincidunt eu, consectetur id mauris. Curabitur nunc augue, luctus sed leo lobortis, cursus consectetur purus. Nam sit amet auctor risus. Maecenas elementum magna id felis venenatis, in ullamcorper ante ultricies. Donec at massa pellentesque, vehicula felis ut, posuere sapien. Curabitur id dignissim est. Cras euismod nisl et rutrum auctor. Nullam sit amet ipsum sed quam molestie consectetur sed eget purus.
          </div>
        </div>
        <div class="item">
          <img src="http://i.istockimg.com/image-zoom/45488504/3/380/314/stock-photo-45488504-highway-in-sunrise.jpg" >
          <div class="carousel-caption">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin blandit mauris vel pellentesque. Praesent congue eros quis metus efficitur accumsan. Sed vel tempus nibh. Donec suscipit quam fringilla ipsum rhoncus tincidunt. Aenean nunc tellus, vulputate vulputate tincidunt eu, consectetur id mauris. Curabitur nunc augue, luctus sed leo lobortis, cursus consectetur purus. Nam sit amet auctor risus. Maecenas elementum magna id felis venenatis, in ullamcorper ante ultricies. Donec at massa pellentesque, vehicula felis ut, posuere sapien. Curabitur id dignissim est. Cras euismod nisl et rutrum auctor. Nullam sit amet ipsum sed quam molestie consectetur sed eget purus.
          </div>
        </div>
        <div class="item">
          <img src="http://i.istockimg.com/image-zoom/45488552/3/380/252/stock-photo-45488552-sunrise.jpg" >
          <div class="carousel-caption">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin blandit mauris vel pellentesque. Praesent congue eros quis metus efficitur accumsan. Sed vel tempus nibh. Donec suscipit quam fringilla ipsum rhoncus tincidunt. Aenean nunc tellus, vulputate vulputate tincidunt eu, consectetur id mauris. Curabitur nunc augue, luctus sed leo lobortis, cursus consectetur purus. Nam sit amet auctor risus. Maecenas elementum magna id felis venenatis, in ullamcorper ante ultricies. Donec at massa pellentesque, vehicula felis ut, posuere sapien. Curabitur id dignissim est. Cras euismod nisl et rutrum auctor. Nullam sit amet ipsum sed quam molestie consectetur sed eget purus.
          </div>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

  </div>
</div>
<br>
<div class="row">
  <div class="col-xs-12">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin blandit mauris vel pellentesque. Praesent congue eros quis metus efficitur accumsan. Sed vel tempus nibh. Donec suscipit quam fringilla ipsum rhoncus tincidunt. Aenean nunc tellus, vulputate vulputate tincidunt eu, consectetur id mauris. Curabitur nunc augue, luctus sed leo lobortis, cursus consectetur purus. Nam sit amet auctor risus. Maecenas elementum magna id felis venenatis, in ullamcorper ante ultricies. Donec at massa pellentesque, vehicula felis ut, posuere sapien. Curabitur id dignissim est. Cras euismod nisl et rutrum auctor. Nullam sit amet ipsum sed quam molestie consectetur sed eget purus.
    </p>
    <p>
      Proin sodales sagittis erat eu lacinia. Phasellus id suscipit libero. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut facilisis luctus turpis mollis aliquam. Ut id lacinia ipsum, sed pellentesque lacus. Aliquam viverra leo sed nibh gravida luctus. Aliquam nec porttitor nibh.
    </p>
    <p>
      Morbi a cursus nisi. Curabitur elementum dui quis lacinia rutrum. In varius purus elit, nec cursus tortor luctus id. Vivamus maximus sed ipsum a tempus. Maecenas id sodales risus, et accumsan diam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam sed mauris a orci sollicitudin commodo et ut dui. Maecenas bibendum imperdiet nisi eget iaculis. Praesent elementum pulvinar felis id pretium. Curabitur ut eros in nisi semper volutpat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla ultrices, turpis vitae tempus facilisis, elit libero dictum diam, non semper enim justo in metus. Vivamus nunc magna, blandit non convallis sit amet, lacinia vitae odio. Pellentesque lobortis tristique sollicitudin. Aliquam sed fermentum tortor. Praesent viverra a lorem eu feugiat.
    </p>
    <p>
      Etiam aliquam tristique mi nec sagittis. Sed ac metus ac purus placerat vulputate. Vestibulum urna elit, placerat a ex eu, rhoncus imperdiet mauris. Maecenas vehicula porta massa, sit amet sagittis dolor pellentesque vestibulum. Cras auctor scelerisque risus non scelerisque. Quisque nec interdum tellus. Donec ultricies, tortor eu mattis efficitur, sem metus consectetur mauris, fermentum gravida purus sem sit amet erat. Nulla mattis orci et augue commodo, eu blandit tellus vulputate. Nullam ullamcorper nunc nibh, pretium scelerisque velit aliquam vel. Vivamus elementum quis lectus feugiat laoreet. Integer in lacinia ligula. Donec at ex in velit venenatis tempor. Sed facilisis sem ac enim auctor, at euismod lectus semper.
    </p>
    <p>
      Quisque ut ipsum quis libero consectetur dignissim. Praesent mollis dictum erat eget vestibulum. Donec vel lorem leo. Quisque ultricies efficitur arcu, eget tincidunt justo viverra at. Aliquam iaculis enim a diam malesuada tristique. Aliquam non maximus orci. Sed ultrices dapibus urna. Morbi sed magna laoreet, faucibus dolor tincidunt, suscipit turpis. Sed viverra pulvinar velit, id lacinia turpis sodales at. Phasellus pretium feugiat felis, ut condimentum mauris lacinia vel. Pellentesque condimentum lectus nec diam rhoncus, eget placerat est porta.
    </p>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<ul>
  <% @user.errors.full_messages.each do |err_msg| %>
    <li><%= err_msg %></li>
  <% end %>
</ul>

<form action="/user" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">


  <div class="row">
    <div class="form-group col-xs-4 col-xs-offset-1">
      <div class="form-group">
        <label for="user_username">Username</label>
        <input class="form-control"
          type="text"
          name="user[username]"
          id="user_username"
          value="<%= @user.username %>">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-xs-4 col-xs-offset-1">
      <div class="form-group">
        <label for="user_password">Password</label>
        <input class="form-control" type="password" name="user[password]" id="user_password">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-xs-4 col-xs-offset-1">
      <input class="btn btn-primary" type="submit" value="Create User!">
    </div>
  </div>
</form>

app/views/users/show.html.erb
<div class="row">
  <div class="form-group col-xs-4 col-xs-offset-1">
    <h1><%= @user.username %></h1>

    <p>Hello, <%= @user.username %></p>

    <p>Current Counter Value: <%= @user.counter %></p>
  </div>
</div>

<form action="/user/counter" method="POST">
  <input type="hidden" name="_method" value="PUT">

  <div class="row">
    <div class="form-group col-xs-4 col-xs-offset-1">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
    </div>
  </div>

  <div class="row">
    <div class="form-group col-xs-4 col-xs-offset-1">
      <label for="user_counter">New Counter Value</label>
      <input type="number" name="user[counter]" id="user_counter">
    </div>
  </div>

  <div class="row">
    <div class="form-group col-xs-4 col-xs-offset-1">
      <input class="brn btn-primary" type="submit" value="Update Counter!">
    </div>
  </div>

</form>

<form action="/session" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <div class="row">
    <div class="form-group col-xs-4 col-xs-offset-1">
      <input class="btn btn-primary" type="submit" value="Logout!">
    </div>
  </div>
</form>